MODULE tipos
IMPLICIT NONE
  ENUM, bind(c)
        ENUMERATOR :: TVD_RK2
        ENUMERATOR :: FORWARD_EULER
  END ENUM
  ENUM, bind(c)
        ENUMERATOR :: ZERO_FLUX
        ENUMERATOR :: PERIODIC
  END ENUM
END MODULE tipos